
logFormat = "Terminal" # one of: Text | Json | Terminal
logLevel = "Debug" #	one of: "Info" # Trace | Info | Debug | Warn | Error | Fatal
testDirectory = "/users/paul/GolandProjects/lfs-imports/testdata/"

[database]
# connections configuration
server = "localhost" # set by environment variables
user = "lfs" # set by environment variables
password = "lfs" # set by environment variables
verbose = false

database = "lfs" # set by environment variables
    [database.connectionPool]
       maxPoolSize = 10
       maxIdleConnections = 2
       maxLifetimeSeconds = 0

[service]

listenAddress = ":8001"
readTimeout = "60s"
writeTimeout = "60s"

[MonthlyTables]
# database tables configuration
postCodeDifferences = "postcode_differences"

